package mb.dnm.code;

public enum DirectoryType {
    LOCAL_SEND,
    LOCAL_RECEIVE,
    LOCAL_TEMP,
    LOCAL_SUCCESS,
    LOCAL_ERROR,
    LOCAL_BACKUP,
    LOCAL_MOVE,
    LOCAL_COPY,
    REMOTE_SEND,
    REMOTE_RECEIVE,
    REMOTE_TEMP,
    REMOTE_SUCCESS,
    REMOTE_ERROR,
    REMOTE_BACKUP,
    REMOTE_MOVE,
    REMOTE_COPY;
}
